---
- name: tage in playbook
  hosts: aws
  become: yes
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state:  present
        update_cache: yes
      tags: install
    - name: start nginx service
      service:
        name: nginx
        state: started
      tags: start
    - name: create a file
      file:
        path: /root/example.txt
        state: touch
        mode: '0644'
        tags: create_file

